export enum Tables {
  Buildings = "buildings",
  BuildingCosts = "building-costs",
  BuildingProduces = "building-produces",
  BuildingReqBuildings = "buildings-req-buildings",
  BuildingReqTechs = "buildings-req-techs",
  BuildingTypes = "building-types",
  BuildingUpkeeps = "building-upkeeps",
  Cannons = "cannons",
  CannonCosts = "cannon-costs",
  CannonReqBuildings = "cannon-req-buildings",
  CannonReqTechs = "cannon-req-techs",
  PushNotifications = "push-notifications",
  Resources = "resources",
  Ships = "ships",
  ShipCosts = "ship-costs",
  ShipReqBuildings = "ship-req-buildings",
  ShipReqTechs = "ship-req-techs",
  ShipUpkeeps = "ship-upkeeps",
  Skills = "skills",
  Techs = "techs",
  TechCosts = "tech-costs",
  TechProduces = "tech-produces",
  TechReqBuildings = "tech-req-buildings",
  TechReqTechs = "tech-req-techs",
  TechTypes = "tech-types",
  Users = "users",
}

export enum EntityName {
  Building = "building",
  BuildingCost = "buildingCost",
  BuildingProduce = "buildingProduce",
  BuildingReqBuilding = "buildingReqBuilding",
  BuildingReqTech = "buildingReqTech",
  BuildingType = "buildingType",
  BuildingUpkeep = "buildingUpkeep",
  Cannon = "cannon",
  CannonCost = "cannonCost",
  CannonReqBuilding = "cannonReqBuilding",
  CannonReqTech = "cannonReqTech",
  PushNotification = "pushNotification",
  Resource = "resource",
  Ship = "ship",
  ShipCost = "shipCost",
  ShipReqBuilding = "shipReqBuilding",
  ShipReqTech = "shipReqTech",
  ShipUpkeep = "shipUpkeep",
  Skill = "skill",
  Tech = "tech",
  TechCost = "techCost",
  TechProduce = "techProduce",
  TechReqBuilding = "techReqBuilding",
  TechReqTech = "techReqTech",
  TechType = "techType",
  User = "user",
}

export enum TablesCamelCase {
  Buildings = "buildings",
  BuildingCosts = "buildingCosts",
  BuildingProduces = "buildingProduces",
  BuildingReqBuildings = "buildingReqBuildings",
  BuildingReqTechs = "buildingReqTechs",
  BuildingTypes = "buildingTypes",
  BuildingUpkeeps = "buildingUpkeeps",
  Cannons = "cannons",
  CannonCosts = "cannonCosts",
  CannonReqBuildings = "cannonReqBuildings",
  CannonReqTechs = "cannonReqTechs",
  PushNotifications = "pushNotifications",
  Resources = "resources",
  Ships = "ships",
  ShipCosts = "shipCosts",
  ShipReqBuildings = "shipReqBuildings",
  ShipReqTechs = "shipReqTechs",
  ShipUpkeeps = "shipUpkeeps",
  Skills = "skills",
  Techs = "techs",
  TechCosts = "techCosts",
  TechProduces = "techProduces",
  TechReqBuildings = "techReqBuildings",
  TechReqTechs = "techReqTechs",
  TechTypes = "techTypes",
  Users = "users",
}

export type APIError = {
  kind: string;
  message: string;
};
